# TypeProf 0.21.3

# Classes
module HackernewsApiClient
  module Responses
    class GetItem
      attr_reader raw_response: ::Faraday::Response
      def initialize: (raw: ::Faraday::Response) -> void
      def as_json: -> Object
    end
  end
end
